---
    - name: Install openldap
      yum: pkg={{item}} state=installed
      with_items:
      - openldap
      - openldap-clients
      - openldap-servers
      - phpldapadmin

    - name: Rsyslog configuration
      template: src=rsyslog.d/{{ item.src }} dest=/etc/rsyslog.d/{{ item.dest }}
      with_items:
        - { src: 'ldap.conf.j2', dest: 'ldap.conf' }
      notify: restart rsyslog

    - name: Enable service slapd
      service: name=slapd enabled=yes state=started

    - name: Copy OpenLDAP ldif
      copy: src={{ item }} dest="{{ download_dir }}"
      with_fileglob:
        - ldif/*
      notify: restart openldap

    - name: Configure OpenLDAP + add base ldifs
      command: "{{ item }}"
      with_items:
      - ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f {{ download_dir }}/config.ldif
      - ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f {{ download_dir }}/logging.ldif
      - ldapadd -c -x -w Password1 -D cn=manager,dc=vagrant,dc=local -H ldapi:/// -f {{ download_dir }}/base.ldif
      ignore_errors: True
      notify: restart openldap
      args:
        creates: /opt/ldap-configured.info

    - name: Configure OpenLDAP with additional ldifs
      command: "ldapadd -Q -Y EXTERNAL -H ldapi:/// -f {{ download_dir }}/{{ item }}"
      with_items: "{{ ldap_additional_ldiff }}"
      ignore_errors: True
      notify: restart openldap
      args:
        creates: /opt/ldap-configured.info

    - name: Configured LDAP
      file: path=/opt/ldap-configured.info  state=touch
      register: ldap_configured
      changed_when: ldap_configured.diff.before.state != "file"

    - name: Copy phpLdapAdmin config
      template: src=phpldapadmin.conf.j2 dest=/etc/httpd/conf.d/phpldapadmin.conf

    - name: Modify phpLdapAdmin configuration
      template: src=phpldapadmin.config.php.j2 dest=/etc/phpldapadmin/config.php
      notify: restart httpd
