---
    - name: Install apache, mod_ssl, wget, vim, unzip
      yum: pkg={{ item }} state=present
      with_items:
      - vim-enhanced
      - httpd
      - mod_ssl
      - wget
      - unzip

    - name: Create download directory
      file: path={{ download_dir }} state=directory

    - name: Create secure directory
      file: path=/var/www/html/secure state=directory

    - name: Download java
      get_url:
        url:     "{{ java_download_location }}"
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
        dest:    "{{ download_dir }}/{{ java_download_file }}"

    - name: Download JCE
      get_url:
        url:     "{{ java_jce_download_location }}"
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
        dest:    "{{ download_dir }}/{{ java_jce_download_file }}" 
    
    - name: Create profile.d files
      template: src=profile.d/{{ item.src }} dest=/etc/profile.d/{{ item.dest }}
      with_items:
        - { src: 'java.sh.j2', dest: 'java.sh' }
        - { src: 'maven.sh.j2', dest: 'maven.sh' }
