---
hostname: "{{ hostname }}"
download_dir: /opt/download
java_download_location: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
java_download_file: jdk-8u181-linux-x64.tar.gz
java_jce_download_location: https://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
java_jce_download_file: jce_policy-8.zip
tomcat_unixgroup: tomcat
tomcat_unixgid: 1000
tomcat_unixuser: tomcat
tomcat_unixuid: 1000
tomcat_installdir: /opt
tomcat_servicename: tomcat
shib_idp_version: 3.3.3
shib_installdir: /opt
shib_home: "{{ shib_installdir }}/shibboleth-idp/"
java_installdir: /opt
java_version: 1.8.0_181
maven_installdir: /opt
tomcat_version: 8.0.30
totp_installdir: /opt
totp_version: 0.5.1
ldap_url: "ldap://localhost:389"
ldap_base_dn: ou=People,dc=vagrant,dc=local
ldap_manager: cn=manager,dc=vagrant,dc=local
ldap_password: Password1
ldap_additional_ldiff:
  - 97-wso2Person.ldif
  - 98-scimPerson.ldif
  - 99-identityPerson.ldif
iptables_flush: true
