---
hostname: "{{ hostname }}"
download_dir: /opt/download
java_download_location: https://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz
java_download_file: jdk-8u172-linux-x64.tar.gz
java_jce_download_location: https://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
java_jce_download_file: jce_policy-8.zip
tomcat_unixgroup: tomcat
tomcat_unixgid: 1000
tomcat_unixuser: tomcat
tomcat_unixuid: 1000
tomcat_installdir: /opt
tomcat_servicename: tomcat
shib_idp_version: 3.2.0
shib_installdir: /opt
shib_home: "{{ shib_installdir }}/shibboleth-idp/"
java_installdir: /opt
java_version: 1.8.0_172
maven_installdir: /opt
tomcat_version: 8.0.30
totp_installdir: /opt
totp_version: 0.5.1
ldap_url: "ldap://localhost:389"
ldap_base_dn: ou=People,dc=vagrant,dc=local
ldap_manager: cn=manager,dc=vagrant,dc=local
ldap_password: Password1
iptables_flush: true
